pretrained_model_path: "stable-diffusion-v1-5/stable-diffusion-v1-5"
output_dir: "path to the output directory"

train_data:
  video_root: "path to the training videos datasets"
  prompt: "a candle burning"
  n_sample_frames: 10
  width: 512
  height: 320
  sample_start_idx: 0
  sample_frame_rate: 1

validation_data:
  image_path: "benchmark/candle"
  prompts:
    - "a candle burning brightly"
    - "a candle burning slightly"
    - "a candle burning in the dark"

  video_length: 9
  width: 512
  height: 320
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: False
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 15000
checkpointing_steps: 3000
validation_steps: 3000
trainable_modules:
  - "conv1d"
  - "conv_gate"
  - "attn1.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
